#!/usr/bin/env python3
# Full AOSP build wrapper; standalone source-only verification invokes the core helper directly.
from pathlib import Path
import os
import re
import runpy
import shutil
import subprocess
import sys

HERE = Path(__file__).resolve().parent
PREP = HERE / "prepare-crosvm-binder-deps.py"
CORE = HERE / "patch-crosvm-gunyah-irqfd-core.py"

if not PREP.is_file():
    raise SystemExit(f"ERROR: missing dependency preflight helper: {PREP}")
if not CORE.is_file():
    raise SystemExit(f"ERROR: missing crosvm patch core helper: {CORE}")
if len(sys.argv) < 2:
    raise SystemExit(f"usage: {Path(sys.argv[0]).name} <path-to-external/crosvm>")

crosvm = Path(sys.argv[1]).resolve()
if not crosvm.is_dir():
    raise SystemExit(f"ERROR: crosvm source directory not found: {crosvm}")
if crosvm.name != "crosvm" or crosvm.parent.name != "external":
    raise SystemExit(f"ERROR: expected <aosp>/external/crosvm, got: {crosvm}")

aosp_root = crosvm.parent.parent
bionic_bp = aosp_root / "bionic/libc/Android.bp"
if not bionic_bp.is_file():
    raise SystemExit(f"ERROR: missing Bionic build definition: {bionic_bp}")

bionic_text = bionic_bp.read_text(encoding="utf-8", errors="ignore")
if '//external/llvm-libc:llvmlibc' not in bionic_text:
    raise SystemExit("ERROR: expected Bionic dependency //external/llvm-libc:llvmlibc is absent")

# Close all dependency projects that are intentionally outside the workflow's
# first minimal manifest selection. ALLOW_MISSING_DEPENDENCIES can defer these
# omissions until Ninja, so sync and validate them before Soong starts.
dependency_projects = (
    "platform/external/llvm-libc",
    "platform/system/libhidl",
    "platform/system/libhwbinder",
    "platform/system/libfmq",
)
print("Syncing deferred crosvm dependency providers: " + ", ".join(dependency_projects))
subprocess.run(
    [
        "repo",
        "sync",
        "-c",
        "-j2",
        "--no-tags",
        "--no-clone-bundle",
        "--force-sync",
        *dependency_projects,
    ],
    cwd=aosp_root,
    check=True,
)

llvm_libc_bp = aosp_root / "external/llvm-libc/Android.bp"
if not llvm_libc_bp.is_file():
    raise SystemExit(f"ERROR: llvm-libc Android.bp missing after sync: {llvm_libc_bp}")
llvm_libc_text = llvm_libc_bp.read_text(encoding="utf-8", errors="ignore")
for required in (
    'name: "llvmlibc"',
    'system_shared_libs: []',
    'header_libs: ["libc_headers"]',
):
    if required not in llvm_libc_text:
        raise SystemExit(f"ERROR: llvm-libc provider validation failed: missing {required}")
print("Verified Bionic provider: //external/llvm-libc:llvmlibc")

# The workflow keeps the complete graphics provider subtree from its initial
# hardware/interfaces checkout. Restore it defensively here as well so the
# patch helper remains safe when invoked outside that workflow.
hw_interfaces = aosp_root / "hardware/interfaces"
if not (hw_interfaces / ".git").exists():
    raise SystemExit(f"ERROR: hardware/interfaces git worktree missing: {hw_interfaces}")

graphics_provider_paths = (
    "graphics",
    "media/1.0",
)
print("Restoring complete frameworks/native graphics HIDL/AIDL/stable-C provider closure")
subprocess.run(
    ["git", "checkout", "HEAD", "--", *graphics_provider_paths],
    cwd=hw_interfaces,
    check=True,
)

# Assert only literal consumer dependencies here. Stable AIDL backend names such
# as android.hardware.graphics.allocator-V2-ndk are generated by Soong from the
# aidl_interface provider and therefore are intentionally validated below at the
# provider/version/API-dump level instead of requiring a literal libui string.
ui_bp = aosp_root / "frameworks/native/libs/ui/Android.bp"
gui_bp = aosp_root / "frameworks/native/libs/gui/Android.bp"
for path in (ui_bp, gui_bp):
    if not path.is_file():
        raise SystemExit(f"ERROR: frameworks/native consumer definition missing: {path}")

ui_text = ui_bp.read_text(encoding="utf-8", errors="ignore")
ui_required = (
    '"android.hardware.graphics.allocator@2.0"',
    '"android.hardware.graphics.allocator@3.0"',
    '"android.hardware.graphics.allocator@4.0"',
    '"android.hardware.graphics.mapper@2.0"',
    '"android.hardware.graphics.mapper@2.1"',
    '"android.hardware.graphics.mapper@3.0"',
    '"android.hardware.graphics.mapper@4.0"',
    '"libimapper_stablec"',
    '"libimapper_providerutils"',
)
ui_missing = [needle for needle in ui_required if needle not in ui_text]
if ui_missing:
    raise SystemExit(f"ERROR: libui literal graphics dependency model drifted: {ui_missing}")

gui_text = gui_bp.read_text(encoding="utf-8", errors="ignore")
gui_required = (
    '"android.hardware.graphics.bufferqueue@1.0"',
    '"android.hardware.graphics.bufferqueue@2.0"',
    '"android.hidl.token@1.0-utils"',
)
gui_missing = [needle for needle in gui_required if needle not in gui_text]
if gui_missing:
    raise SystemExit(f"ERROR: libgui graphics dependency model drifted: {gui_missing}")

provider_checks = {
    aosp_root / "hardware/interfaces/graphics/allocator/2.0/Android.bp": (
        'name: "android.hardware.graphics.allocator@2.0"',
        '"android.hardware.graphics.mapper@2.0"',
    ),
    aosp_root / "hardware/interfaces/graphics/allocator/3.0/Android.bp": (
        'name: "android.hardware.graphics.allocator@3.0"',
        '"android.hardware.graphics.mapper@3.0"',
        '"android.hardware.graphics.common@1.2"',
    ),
    aosp_root / "hardware/interfaces/graphics/allocator/4.0/Android.bp": (
        'name: "android.hardware.graphics.allocator@4.0"',
        '"android.hardware.graphics.mapper@4.0"',
        '"android.hardware.graphics.common@1.2"',
    ),
    aosp_root / "hardware/interfaces/graphics/allocator/aidl/Android.bp": (
        'name: "android.hardware.graphics.allocator"',
        'vndk_use_version: "2"',
        'version: "2"',
        'frozen: true',
        'ndk: {',
        '"android.hardware.common-V2"',
        '"android.hardware.graphics.common-V4"',
    ),
    aosp_root / "hardware/interfaces/common/aidl/Android.bp": (
        'name: "android.hardware.common"',
        'version: "2"',
    ),
    aosp_root / "hardware/interfaces/graphics/common/aidl/Android.bp": (
        'name: "android.hardware.graphics.common"',
        'version: "4"',
        '"android.hardware.common-V2"',
    ),
    aosp_root / "hardware/interfaces/graphics/mapper/stable-c/Android.bp": (
        'name: "libimapper_stablec"',
        'name: "libimapper_providerutils"',
        '"libarect_headers"',
        '"libbase_headers"',
    ),
    aosp_root / "hardware/interfaces/graphics/mapper/2.0/Android.bp": (
        'name: "android.hardware.graphics.mapper@2.0"',
        '"android.hardware.graphics.common@1.0"',
    ),
    aosp_root / "hardware/interfaces/graphics/mapper/2.1/Android.bp": (
        'name: "android.hardware.graphics.mapper@2.1"',
        '"android.hardware.graphics.mapper@2.0"',
        '"android.hardware.graphics.common@1.1"',
    ),
    aosp_root / "hardware/interfaces/graphics/mapper/3.0/Android.bp": (
        'name: "android.hardware.graphics.mapper@3.0"',
        '"android.hardware.graphics.common@1.2"',
    ),
    aosp_root / "hardware/interfaces/graphics/mapper/4.0/Android.bp": (
        'name: "android.hardware.graphics.mapper@4.0"',
        '"android.hardware.graphics.common@1.2"',
    ),
    aosp_root / "hardware/interfaces/graphics/common/1.0/Android.bp": (
        'name: "android.hardware.graphics.common@1.0"',
    ),
    aosp_root / "hardware/interfaces/graphics/common/1.1/Android.bp": (
        'name: "android.hardware.graphics.common@1.1"',
    ),
    aosp_root / "hardware/interfaces/graphics/common/1.2/Android.bp": (
        'name: "android.hardware.graphics.common@1.2"',
    ),
    aosp_root / "hardware/interfaces/graphics/bufferqueue/1.0/Android.bp": (
        'name: "android.hardware.graphics.bufferqueue@1.0"',
        '"android.hardware.media@1.0"',
        '"android.hidl.base@1.0"',
    ),
    aosp_root / "hardware/interfaces/graphics/bufferqueue/2.0/Android.bp": (
        'name: "android.hardware.graphics.bufferqueue@2.0"',
        '"android.hardware.graphics.common@1.2"',
        '"android.hidl.base@1.0"',
    ),
    aosp_root / "hardware/interfaces/media/1.0/Android.bp": (
        'name: "android.hardware.media@1.0"',
        '"android.hardware.graphics.common@1.0"',
    ),
    aosp_root / "system/libhidl/Android.bp": (
        'name: "libhidlbase"',
        'name: "libhidltransport"',
    ),
    aosp_root / "system/libhidl/transport/base/1.0/Android.bp": (
        'name: "android.hidl.base@1.0"',
    ),
    aosp_root / "system/libhidl/transport/token/1.0/utils/Android.bp": (
        'name: "android.hidl.token@1.0-utils"',
    ),
    aosp_root / "system/libhwbinder/Android.bp": (
        'name: "libhwbinder"',
        'name: "libhwbinder-impl-internal"',
    ),
    aosp_root / "system/libfmq/Android.bp": (
        'name: "libfmq-base"',
    ),
}
for path, needles in provider_checks.items():
    if not path.is_file():
        raise SystemExit(f"ERROR: graphics/HIDL provider missing: {path}")
    text = path.read_text(encoding="utf-8", errors="ignore")
    missing = [needle for needle in needles if needle not in text]
    if missing:
        raise SystemExit(f"ERROR: provider validation failed for {path}: {missing}")

# Validate the frozen Stable-AIDL snapshots that cause Soong to materialize the
# generated -V*-ndk modules used by the native graphics dependency graph.
aidl_snapshot_dirs = (
    aosp_root / "hardware/interfaces/common/aidl/aidl_api/android.hardware.common/2",
    aosp_root / "hardware/interfaces/graphics/common/aidl/aidl_api/android.hardware.graphics.common/4",
    aosp_root / "hardware/interfaces/graphics/allocator/aidl/aidl_api/android.hardware.graphics.allocator/2",
)
for path in aidl_snapshot_dirs:
    if not path.is_dir():
        raise SystemExit(f"ERROR: Stable AIDL snapshot missing: {path}")
    if not (path / ".hash").is_file():
        raise SystemExit(f"ERROR: Stable AIDL snapshot hash missing: {path / '.hash'}")
print(
    "Verified generated Stable-AIDL providers: android.hardware.common-V2, "
    "android.hardware.graphics.common-V4 and android.hardware.graphics.allocator-V2-ndk"
)

# The workflow creates ownership-only team stubs before this late provider sync
# and restore. Refresh them so any default_team/team references introduced by
# llvm-libc, libhidl or the restored HAL Android.bp files cannot become the next
# Soong failure.
team_stub_root = aosp_root / "local-missing-teams"
if team_stub_root.exists():
    shutil.rmtree(team_stub_root)
team_stub_root.mkdir(parents=True, exist_ok=True)

ref_re = re.compile(r'\b(?:team|default_team)\s*:\s*"(?P<name>trendy_team_[^"]+)"')
name_re = re.compile(r'\bname\s*:\s*"(?P<name>trendy_team_[^"]+)"')
refs, defs = set(), set()
for base, dirs, files in os.walk(aosp_root):
    dirs[:] = [
        d
        for d in dirs
        if d not in {".repo", "out", "local-missing-teams"}
    ]
    if "Android.bp" not in files:
        continue
    bp = Path(base) / "Android.bp"
    text = bp.read_text(encoding="utf-8", errors="ignore")
    refs.update(m.group("name") for m in ref_re.finditer(text))
    defs.update(m.group("name") for m in name_re.finditer(text))

missing_teams = sorted(refs - defs)
team_bp = team_stub_root / "Android.bp"
with team_bp.open("w", encoding="utf-8") as f:
    f.write("// Generated ownership-only team stubs after late provider closure.\n\n")
    for name in missing_teams:
        f.write("team {\n")
        f.write(f'    name: "{name}",\n')
        f.write(f'    trendy_team_id: "{name}",\n')
        f.write("}\n\n")
print(f"Refreshed {len(missing_teams)} missing trendy team stub(s)")

print(
    "Verified graphics/HIDL follow-on closure: "
    "full graphics subtree + stable-C IMapper + allocator/common AIDL + "
    "legacy allocator/mapper/bufferqueue + media@1.0 + libhidl/libhwbinder/libfmq"
)

subprocess.run([sys.executable, str(PREP), *sys.argv[1:]], check=True)
runpy.run_path(str(CORE), run_name="__main__")
