name: Run Enhanced SukiSU SUSFS Once
run-name: "Enhanced SukiSU SUSFS — 6.1.145-android14-11-33419968-abS928BXXS6DZG1"

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    uses: ./.github/workflows/kernel-custom.yml
    permissions:
      contents: write
      actions: write
    with:
      kernel_target: "android14-6.1.145 (2025-09)"
      quick_target: ""
      ksu_variant: "SukiSU"
      add_susfs: true
      add_zeromount: true
      add_droidspaces: true
      add_zram: true
      add_bbg: true
      add_overlayfs_support: true
      add_kpm: true
      susfs_open_redirect: true
      sukisu_commit: ""
# Manual start only after the one-time rebuild trigger.
